const crypto=require('crypto');
const DISCORD='https://discord.com/api/v10',GUILD=process.env.DISCORD_GUILD_ID||'1548652649866596473',BOT=process.env.DISCORD_BOT_TOKEN,CLIENT=process.env.DISCORD_CLIENT_ID,SECRET=process.env.DISCORD_CLIENT_SECRET,SUPA=process.env.SUPABASE_URL,SKEY=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY,SITE=process.env.SITE_URL,SESSION=process.env.SESSION_SECRET;
const json=(r)=>new Promise((res,rej)=>{let b='';r.on('data',x=>b+=x);r.on('end',()=>{try{res(JSON.parse(b||'{}'))}catch(e){rej(e)}});r.on('error',rej)});
const send=(res,s,d,h={})=>{res.statusCode=s;for(const[k,v]of Object.entries(h))res.setHeader(k,v);res.setHeader('Content-Type','application/json');res.end(JSON.stringify(d))};
function sign(x){return crypto.createHmac('sha256',SESSION).update(x).digest('base64url')}function enc(x){return Buffer.from(x).toString('base64url')}function dec(x){return Buffer.from(x,'base64url').toString()}
const SESSION_MAX_AGE=60*60*24*365*10;
function setCookie(name,value,max){const expires=max<=0?'; Expires=Thu, 01 Jan 1970 00:00:00 GMT':`; Expires=${new Date(Date.now()+max*1000).toUTCString()}`; return `${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${max}${expires}; Priority=High`}
function noStore(res){res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, private');res.setHeader('Pragma','no-cache');res.setHeader('Expires','0')}
function session(req){const m=(req.headers.cookie||'').match(/pc_session=([^;]+)/);if(!m)return null;try{const[a,b]=m[1].split('.');if(!a||!b||b!==sign(a))return null;const x=JSON.parse(dec(a));return x.exp>Date.now()?x.u:null}catch{return null}}
function sessionCookie(u){const payload=enc(JSON.stringify({u,exp:Date.now()+SESSION_MAX_AGE*1000}));return setCookie('pc_session',payload+'.'+sign(payload),SESSION_MAX_AGE)}
async function db(path,opt={}){return fetch(`${SUPA}/rest/v1/${path}`,{...opt,headers:{apikey:SKEY,Authorization:`Bearer ${SKEY}`,'Content-Type':'application/json',...(opt.headers||{})}}).then(async r=>({ok:r.ok,status:r.status,data:await r.json().catch(()=>null)}))}
async function dapi(path,opt={}){return fetch(DISCORD+path,{...opt,headers:{Authorization:`Bot ${BOT}`,'Content-Type':'application/json',...(opt.headers||{})}}).then(async r=>({ok:r.ok,status:r.status,data:await r.json().catch(()=>null)}))}
function avatar(u){return u.avatar?`https://cdn.discordapp.com/avatars/${u.id}/${u.avatar}.png?size=128`:'https://cdn.discordapp.com/embed/avatars/0.png'}
async function ban(id){const r=await dapi(`/guilds/${GUILD}/bans/${id}`);return r.ok?r.data:null}
async function cases(id,source){const q=`guild_id=eq.${encodeURIComponent(GUILD)}&user_id=eq.${encodeURIComponent(id)}&source=eq.${encodeURIComponent(source)}&order=created_at.desc&select=*`;const r=await db(`moderation_cases?${q}`);return r.ok?r.data||[]:[]}
module.exports=async(req,res)=>{try{noStore(res);const u=new URL(req.url,`https://${req.headers.host}`),p=u.pathname;
if(p==='/api/login'){const st=enc(crypto.randomBytes(24));res.statusCode=302;res.setHeader('Set-Cookie',setCookie('pc_state',st,600));res.setHeader('Location',`https://discord.com/oauth2/authorize?client_id=${encodeURIComponent(CLIENT)}&response_type=code&redirect_uri=${encodeURIComponent(SITE+'/api/callback')}&scope=identify&state=${st}`);return res.end()}
if(p==='/api/callback'){const code=u.searchParams.get('code'),st=u.searchParams.get('state'),m=(req.headers.cookie||'').match(/pc_state=([^;]+)/);if(!code||!st||!m||m[1]!==st)return send(res,400,{error:'Ungültige Anmeldung.'});const body=new URLSearchParams({client_id:CLIENT,client_secret:SECRET,grant_type:'authorization_code',code,redirect_uri:SITE+'/api/callback'});const t=await fetch(DISCORD+'/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const td=await t.json();const me=await fetch(DISCORD+'/users/@me',{headers:{Authorization:`Bearer ${td.access_token}`}}).then(r=>r.ok?r.json():null);if(!me)return send(res,401,{error:'Discord Anmeldung fehlgeschlagen.'});const user={id:me.id,username:me.username,global_name:me.global_name,avatar:avatar(me)};res.statusCode=302;res.setHeader('Set-Cookie',sessionCookie(user));res.setHeader('Location','/');return res.end()}
const me=session(req);if(!me)return send(res,401,{error:'Nicht angemeldet.'});
if(p==='/api/me'){res.setHeader('Set-Cookie',sessionCookie(me));const b=await ban(me.id),ws=await cases(me.id,'discord');const link=await db(`roblox_links?discord_id=eq.${me.id}&select=*`);const rl=link.ok?(link.data||[])[0]:null;let rc=[];if(rl){const q=`guild_id=eq.${GUILD}&source=eq.roblox&roblox_username=ilike.${encodeURIComponent(rl.username)}&order=created_at.desc&select=*`;const rr=await db(`moderation_cases?${q}`);rc=rr.ok?rr.data||[]:[]}const ap=await db(`appeals?discord_id=eq.${me.id}&order=created_at.desc&select=*`);return send(res,200,{user:me,banned:!!b,ban:b?{reason:b.reason}:null,warns:ws.filter(x=>['warn','discord_warn'].includes(String(x.action).toLowerCase())),roblox:{username:rl?.username||null,cases:rc},appeals:ap.ok?ap.data||[]:[]})}
if(p==='/api/roblox'&&req.method==='POST'){const x=await json(req),name=String(x.username||'').trim();if(!/^[A-Za-z0-9_]{3,20}$/.test(name))return send(res,400,{error:'Ungültiger Roblox Benutzername.'});const existing=await db(`roblox_links?discord_id=eq.${encodeURIComponent(me.id)}&select=*`);if(!existing.ok)return send(res,500,{error:'Roblox Verknüpfung konnte nicht geprüft werden.'});if(existing.data?.length)return send(res,409,{error:'Dein Roblox Benutzername wurde bereits fest hinterlegt und kann nicht geändert werden.'});const r=await db('roblox_links',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({discord_id:me.id,username:name,updated_at:new Date().toISOString()})});return send(res,r.ok?200:500,r.ok?{ok:true}:{error:'Roblox Name konnte nicht gespeichert werden.'})}
if(p==='/api/appeals'&&req.method==='POST'){const x=await json(req),type=String(x.type||''),reason=String(x.reason||'').trim(),caseId=x.case_id?String(x.case_id):null;if(!['discord_ban','discord_warn','roblox'].includes(type)||reason.length<10||reason.length>2000)return send(res,400,{error:'Ungültiger Antrag.'});if(type==='discord_ban'&&!(await ban(me.id)))return send(res,400,{error:'Du bist aktuell nicht gebannt.'});if(type!=='discord_ban'&&!caseId)return send(res,400,{error:'Kein Fall ausgewählt.'});if(caseId){const r=await db(`moderation_cases?guild_id=eq.${GUILD}&case_id=eq.${encodeURIComponent(caseId)}&select=*`);if(!r.ok||!r.data?.[0]||String(r.data[0].user_id)!==String(me.id))return send(res,403,{error:'Dieser Fall gehört nicht zu dir.'})}const appealData={discord_id:me.id,discord_username:me.username,type,case_id:caseId,reason,status:'open',created_at:new Date().toISOString()};let r=await db('appeals',{method:'POST',body:JSON.stringify({...appealData,discord_notified:false,bot_handled:false})});if(!r.ok){r=await db('appeals',{method:'POST',body:JSON.stringify(appealData)})}if(!r.ok){console.error('Supabase appeals insert failed:',r.status,r.data);return send(res,500,{error:'Der Antrag konnte nicht gespeichert werden. Supabase: '+(r.data?.message||r.data?.hint||r.data?.details||('HTTP '+r.status))})}return send(res,200,{ok:true})}
return send(res,404,{error:'Nicht gefunden.'})}catch(e){console.error(e);return send(res,500,{error:'Interner Fehler.'})}};
